// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Slp.Fsm.Tests")>]
[<assembly: AssemblyProductAttribute("Slp.Fsm")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-06-12T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","beta")>]
[<assembly: AssemblyMetadataAttribute("GitHash","12e1f49f0978641529b258292e85d0a8fec5a544")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Slp.Fsm.Tests"
    let [<Literal>] AssemblyProduct = "Slp.Fsm"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-06-12T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "beta"
    let [<Literal>] AssemblyMetadata_GitHash = "12e1f49f0978641529b258292e85d0a8fec5a544"
