// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Slp.Fsm")>]
[<assembly: AssemblyProductAttribute("Slp.Fsm")>]
[<assembly: AssemblyVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-06-22T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","23d1a7c669477c2eb2b10c9cba372b1fc5b13491")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Slp.Fsm"
    let [<Literal>] AssemblyProduct = "Slp.Fsm"
    let [<Literal>] AssemblyVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-06-22T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "0.1.1"
    let [<Literal>] AssemblyInformationalVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "23d1a7c669477c2eb2b10c9cba372b1fc5b13491"
